name: 'build'
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codebase'
        if: github.event_name == 'push'
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: 'Checkout codebase'
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: cachix/install-nix-action@v14
      - run: NIXPKGS_ALLOW_UNFREE=1 nix --experimental-features 'nix-command flakes' build -L --impure
      - name: 'Copy book'
        run: cp result/share/book.pdf .
      - name: 'Upload artifact to GitHub'
        uses: actions/upload-artifact@v2.2.4
        with:
          name: book.pdf
          path: book.pdf
